version: '3'

networks:
  controller_net:
    name: controller_net
  view_net:
    name: view_net

services:
  view:
    container_name: frontend
    build:
      context: frontend
    image: front-image
    restart: always
    depends_on:
      - back
    expose:
      - 5067
    networks:
      - view_net
    ports:
      - 5067:5067

  back:
    container_name: backend
    build:
      context: backend
    image: back-image
    networks:
      - view_net
      - controller_net
    expose:
      - 5103
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=CarShop
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    networks:
      - controller_net
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    container_name: proxy
    image: nginx
    volumes:
      - images-volume:/api/v1/images
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8000:8000
    depends_on:
      - view
      - back
    networks:
      - view_net

volumes:
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: storage/database

  images-volume:
    name: images-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: storage/images

secrets:
  db-password:
    file: db/db-password.txt
