version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=CarShop
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: storage/database

secrets:
  db-password:
    file: db/db-password.txt
