version: '3'

networks:
  controller_net:
    name: controller_net
  view_net:
    name: view_net

services:

  back:
    container_name: backend
    build:
      context: backend
    image: back-image
    secrets:
      - secrets_env
    environment:
      ConnectionStrings__DefaultConn: "Server=${POSTGRESSQL_DB_SERVER}; DataBase=${POSTGRESSQL_DB_NAME}; Uid=${POSTGRESSQL_USER_NAME}; Pwd=${POSTGRESSQL_USER_PASSWORD}"
      ConnectionStrings__LoggerDir: "${LOGGER_DIR}"
      JWT__SecretKey: "${JWT__SecretKey}"
      JWT__ValidAudience: "${JWT__ValidAudience}"
      JWT__ValidIssuser: "${JWT__ValidIssuser}"
      JWT__TokenValidityInMinutes: "${JWT__TokenValidityInMinutes}"
      JWT__RefreshTokenValidityInMinutes: "${JWT__RefreshTokenValidityInMinutes}"
    networks:
      - view_net
      - controller_net
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
      - secrets_env
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRESSQL_DB_NAME}"
      POSTGRES_USER: "${POSTGRESSQL_USER}"
      POSTGRES_PASSWORD: "${POSTGRESSQL_USER_PASSWORD}"
    expose:
      - 5432
    networks:
      - controller_net
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    container_name: proxy
    build:
      context: frontend
    image: nginx
    volumes:
      - images-volume:/api/v1/images
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - back
    networks:
      - view_net

volumes:
  db-volume:
    name: db-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: storage/database

  images-volume:
    name: images-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: storage/images

secrets:
  db-password:
    file: db/db-password.txt
  secrets_env:
    file: .env
